### ISSUE TITLE
poopoo

### ISSUE THREAD

**Issue by sepruko** [vizality-community/status-everywhere#1]
peepee

**Comment by dperolio** [comment]
> Plugin should ignore both the webhooks and system account(s) as their statuses are never visible to the user on a vanilla install of the client and have no use for being seen.

Good points. I'm not really sure how to do it with JS, but it's easily enough done with CSS, coupled with Vizality's inserted message attributes. Thanks to your suggestion, I added a couple more (vz-local and vz-webhook) to messages for this. Hopefully that's good enough. Added.

> Clicking on a profile picture in the chat repeatedly will just open the profile popout instead of alternating between opening and closing it as it should (if popout is opened, close it and if not, open it).

I knew about this, but unfortunately, I don't have any immediate answer to it. I'm using the old popouts (currently referred to as DeprecatedPopout by Discord) for this and haven't really figured out the new ones yet. On the new popouts they simple toggle a state of `shouldShow`. I'll leave this open as a reminder that this issue exists until I can come up with a solution.

Thanks.

**Comment by WinstonSepruko** [comment]
I'm not sure how performance friendly this would be, but perhaps you could set up a system that caches webhooks after using a message's flags to determine whether or not a webhook sent the message.

Messages send by webhooks have a `webhookId` flag.

**Comment by dperolio** [comment]
> I'm not sure how performance friendly this would be, but perhaps you could set up a system that caches webhooks after using a message's flags to determine whether or not a webhook sent the message.
> 
> Messages sent by webhooks have a `webhookId` flag.

Yes, that's how I added the vz-webhook attribute to messages. EDIT: Oh, sorry, forgot to push the change on the Vizality repo.
