### ISSUE TITLE
StatusEverywhere.plugin.js cannot be compiled

### ISSUE THREAD

**Issue by SwiftWinds** [vizality-community/status-everywhere#3]
Sorry, I feel this is a noob question, but when I rename the index.js to StatusEverywhere.plugin.js and put it in my plugins folder, BetterDiscord says:

```js
StatusEverywhere.plugin.js: Could not be compiled.
    at Object.loadAddon (<anonymous>:4:190848)
    at Object.loadAddon (<anonymous>:4:228205)
    at FSWatcher.<anonymous> (<anonymous>:4:189109)
```

Does this need to be transpiled from jsx to js or something?

**Comment by yellowsink** [comment]
Vizality plugins are for Vizality and not BetterDiscord. It won't work.

**Comment by SwiftWinds** [comment]
Ah guess I'm in the wrong place because I've admittedly never heard of Vizality. Does it support BetterDiscord plugins? I might migrate over (once Vizality is released).

**Comment by vbajs** [comment]
Yes. There's Bdcompat for Vizality that adds a compatibility layer for BetterDiscord plugins

Note that Vizality plugins do not work in any other cilent mod than Vizality (unless some sort of vizality compatibility layer is made)

**Comment by resucutie** [comment]
yeah, there is vz-bdcompat but eh its a pretty bad port of the original BDCompat from Powercord. I have plans to rewrite it, but eh if i did had enough free time i would do the rewrite

**Comment by SwiftWinds** [comment]
OK, I look forward to the public release!

**Comment by Miniontoby** [comment]
How to use this plugin? Cause I cannot see StatusEverywhere.plugin.js anywhere...

**Comment by lol219** [comment]
Vizality is broken...

**Comment by yellowsink** [comment]
> Vizality is broken...

All classic client mods have been broken since September.
https://cumcord.com/an-exercise-in-futility

**Comment by lol219** [comment]
You are late , some clients has fixed the crashes and some survived , vizality is massively broken

**Comment by yellowsink** [comment]
> some clients has fixed the crashes and some survived

The client mods worth using at the moment are the new ones created after the fact, no disrespect intended to those working on replugged and bd

**Comment by xhyrom** [comment]
> > some clients has fixed the crashes and some survived
> 
> The client mods worth using at the moment are the new ones created after the fact, no disrespect intended to those working on replugged and bd

yep, agree
